In [45]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Wgrywanie danych

In [46]:
asysty = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Asysty.csv")
asysty.head()

,Lp.,Zawodnik,Drużyna,Mecze,Asysty suma,Asysty śr.
0,1,Maurice Watson,Twarde Pierniki Toruń,7,71,10.1
1,2,Branden Frazier,Enea Zastal BC Zielona Góra,7,63,9.0
2,3,Jakub Schenk,King Szczecin,7,55,7.9
3,4,Jabarie Hinds,GTK Gliwice,7,48,6.9
4,5,Erick Neal,PGE Spójnia Stargard,7,47,6.7

In [47]:
bloki = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Bloki.csv")
bloki.head()

,Lp.,Zawodnik,Drużyna,Mecze,Bloki suma,Bloki śr,Bloki otrzymane suma,Bloki otrzymane śr
0,1,Joshua Sharma,Trefl Sopot,7,21,3.00,3,0.43
1,2,Filip Kraljević,HydroTruck Radom,7,17,2.43,2,0.29
2,3,Klavs Čavars,Enea Abramczyk Astoria Bydgoszcz,7,13,1.86,4,0.57
3,4,Cyril Langevine,WKS Śląsk Wrocław,8,9,1.13,6,0.75
4,5,Kavell Bigby-Williams,Anwil Włocławek,7,9,1.29,2,0.29

In [48]:
czas_gry = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Czas_gry.csv")
czas_gry.head()

,Lp.,Zawodnik,Drużyna,Mecze,Czas gry suma,Czas gry śr.
0,1,Michael Moore,HydroTruck Radom,8,261:07,32:38
1,2,William Garrett,Grupa Sierleccy Czarni Słupsk,7,243:15,34:45
2,3,Marek Klassen,Grupa Sierleccy Czarni Słupsk,7,239:11,34:10
3,4,Maurice Watson,Twarde Pierniki Toruń,7,237:39,33:57
4,5,A.j. English,HydroTruck Radom,7,233:16,33:19

In [49]:
eval = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Eval.csv")
eval.head()

,Lp.,Zawodnik,Drużyna,Mecze,+/- suma,+/- śr.,Eval suma,Eval śr.
0,1,Łukasz Koszarek,Legia Warszawa,6,67,11.17,84,14.0
1,2,James Bell,Anwil Włocławek,7,66,9.43,72,10.3
2,3,Jure Škifić,Legia Warszawa,6,65,10.83,42,7.0
3,4,Grzegorz Kamiński,Legia Warszawa,6,65,10.83,36,6.0
4,5,Luke Petrasek,Anwil Włocławek,7,63,9.00,112,16.0

In [50]:
faule = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Faule.csv")
faule.head()

,Lp.,Zawodnik,Drużyna,Mecze,Faule suma,Faule śr.,Faule wymuszone suma,Faule wymuszone śr.
0,1,Joshua Sharma,Trefl Sopot,7,27,3.86,16,2.29
1,2,Jakub Schenk,King Szczecin,7,27,3.86,28,4.00
2,3,Dragan Apić,Enea Zastal BC Zielona Góra,7,26,3.71,44,6.29
3,4,Novak Musić,Asseco Arka Gdynia,6,25,4.17,27,4.50
4,5,Adam Ramstedt,GTK Gliwice,7,25,3.57,17,2.43

In [51]:
przechwyty = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Przechwyty.csv")
przechwyty.head()

,Lp.,Zawodnik,Drużyna,Mecze,Przechwyty suma,Przechwyty śr
0,1,Sherron Dorsey-Walker,King Szczecin,7,19,2.71
1,2,Mateusz Zębski,Enea Abramczyk Astoria Bydgoszcz,7,18,2.57
2,3,Aaron Cel,Twarde Pierniki Toruń,7,15,2.14
3,4,Jakub Schenk,King Szczecin,7,13,1.86
4,5,Jonah Mathews,Anwil Włocławek,7,13,1.86

In [52]:
punkty = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Punkty.csv")
punkty.head()

,Lp.,Zawodnik,Drużyna,Mecze,Punkty suma,Punkty śr.
0,1,A.j. English,HydroTruck Radom,7,153,21.86
1,2,William Garrett,Grupa Sierleccy Czarni Słupsk,7,142,20.29
2,3,Jabarie Hinds,GTK Gliwice,7,137,19.57
3,4,Stacy Davis,King Szczecin,7,127,18.14
4,5,Michael Moore,HydroTruck Radom,8,126,15.75

In [53]:
rzuty_wolne = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Rzuty_wolne.csv")
rzuty_wolne.head()

,Lp.,Zawodnik,Drużyna,Mecze,Celne rzuty wolne suma,Celne rzuty wolne śr.,Oddane rzuty wolne suma,Oddane rzuty wolne śr.,Skuteczność za 1
0,1,William Garrett,Grupa Sierleccy Czarni Słupsk,7,43,6.1,54,7.7,79.6
1,2,Joshua Sharkey,Polski Cukier Pszczółka Start Lublin,7,34,4.9,45,6.4,75.6
2,3,Filip Kraljević,HydroTruck Radom,7,33,4.7,38,5.4,86.8
3,4,A.j. English,HydroTruck Radom,7,33,4.7,42,6.0,78.6
4,5,Michael Lewis II,MKS Dąbrowa Górnicza,7,32,4.6,36,5.1,88.9

In [54]:
rzuty_z_gry = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Rzuty_z_gry.csv")
rzuty_z_gry.head()

,Lp.,Zawodnik,Drużyna,Mecze,Celne rzuty z gry suma,Celne rzuty z gry śr.,Oddane rzuty z gry suma,Oddane rzuty z gry śr.,Skuteczność z gry
0,1,Jonah Mathews,Anwil Włocławek,7,48,6.9,100,14.3,48.0
1,2,Dragan Apić,Enea Zastal BC Zielona Góra,7,48,6.9,77,11.0,62.3
2,3,Stacy Davis,King Szczecin,7,48,6.9,99,14.1,48.5
3,4,A.j. English,HydroTruck Radom,7,47,6.7,99,14.1,47.5
4,5,Jabarie Hinds,GTK Gliwice,7,47,6.7,95,13.6,49.5

In [55]:
rzuty_za_2 = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Rzuty_za_2.csv")
rzuty_za_2.head()

,Lp.,Zawodnik,Drużyna,Mecze,Celne rzuty za 2 suma,Celne rzuty za 2 śr.,Oddane rzuty za 2 suma,Oddane rzuty za 2 śr.,Skuteczność za 2
0,1,Dragan Apić,Enea Zastal BC Zielona Góra,7,48,6.9,77,11.0,62.3
1,2,Kyndall Dykes,Anwil Włocławek,7,41,5.9,70,10.0,58.6
2,3,Stacy Davis,King Szczecin,7,39,5.6,74,10.6,52.7
3,4,Trevor Thompson,Twarde Pierniki Toruń,7,39,5.6,77,11.0,50.6
4,5,Maurice Watson,Twarde Pierniki Toruń,7,39,5.6,75,10.7,52.0

In [56]:
rzuty_za_3 = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Rzuty_za_3.csv")
rzuty_za_3.head()

,Lp.,Zawodnik,Drużyna,Mecze,Celne rzuty za 3 suma,Celne rzuty za 3 śr.,Oddane rzuty za 3 suma,Oddane rzuty za 3 śr.,Skuteczność za 3
0,1,A.j. English,HydroTruck Radom,7,26,3.7,59,8.4,44.1
1,2,Yannick Franke,Trefl Sopot,7,22,3.1,52,7.4,42.3
2,3,Raymond Cowels III,Legia Warszawa,6,21,3.5,47,7.8,44.7
3,4,James Florence,Arged BM Stal Ostrów Wlkp.,7,20,2.9,48,6.9,41.7
4,5,Roberts Stumbris,GTK Gliwice,7,20,2.9,36,5.1,55.6

In [57]:
straty = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Straty.csv")
straty.head()

,Lp.,Zawodnik,Drużyna,Mecze,Straty suma,Straty śr.
0,1,Erick Neal,PGE Spójnia Stargard,7,27,3.86
1,2,Jakub Schenk,King Szczecin,7,26,3.71
2,3,Joshua Sharkey,Polski Cukier Pszczółka Start Lublin,7,24,3.43
3,4,A.j. English,HydroTruck Radom,7,23,3.29
4,5,Jabarie Hinds,GTK Gliwice,7,23,3.29

In [58]:
zbiorki = pd.read_csv("/home/szymonf/Documents/Data Science tasks/Energa Basket Liga Statystyki /Date statystyczne indywidualne Energa Basket Liga/Zbiorki.csv")
zbiorki.head()

,Lp.,Zawodnik,Drużyna,Mecze,Zbiórki w ataku suma,Zbiórki w ataku śr.,Zbiórki w obronie suma,Zbiórki w obronie śr.,Zbiórki suma,Zbiórki śr
0,1,Klavs Čavars,Enea Abramczyk Astoria Bydgoszcz,7,29,4.1,34,4.9,63,9.00
1,2,Cyril Langevine,WKS Śląsk Wrocław,8,22,2.8,27,3.4,49,6.13
2,3,Mikołaj Witliński,Grupa Sierleccy Czarni Słupsk,7,17,2.4,13,1.9,30,4.29
3,4,Trevor Thompson,Twarde Pierniki Toruń,7,17,2.4,40,5.7,57,8.14
4,5,Jonas Zohore,PGE Spójnia Stargard,7,15,2.1,33,4.7,48,6.86

# Czyścimy oraz łączymy wgrane pliki csv!

## Zrobienie indeksu z kolumny "Zawodnik"

### Tworzymy dataFrame, ktory zawiera wszystkie kolumny, które posiadają wszystkie inne kolumny, czyli "Zawodnik","Drużyna" oraz "Mecze"

In [59]:
mecze = punkty[["Zawodnik","Drużyna","Mecze"]]
mecze.set_index(mecze["Zawodnik"], inplace=True)
mecze = mecze.drop("Zawodnik", axis=1, inplace=False)
mecze.head()

                                        Drużyna  Mecze
Zawodnik
A.j. English                  HydroTruck Radom       7
William Garrett  Grupa Sierleccy Czarni Słupsk       7
Jabarie Hinds                      GTK Gliwice       7
Stacy Davis                      King Szczecin       7
Michael Moore                 HydroTruck Radom       8

In [60]:
zbior_plikow = [asysty,bloki,czas_gry,eval,faule,przechwyty,punkty,rzuty_wolne,rzuty_z_gry,rzuty_za_2,rzuty_za_3,straty,zbiorki]

i = 0
while i<len(zbior_plikow):
    zbior_plikow[i].set_index(zbior_plikow[i]["Zawodnik"], inplace=True)
    zbior_plikow[i] = zbior_plikow[i].drop(["Lp.","Zawodnik","Drużyna","Mecze"], axis=1, inplace=True)
    i+=1
bloki

,Bloki suma,Bloki śr,Bloki otrzymane suma,Bloki otrzymane śr
Zawodnik,,,,
Joshua Sharma,21,3.00,3,0.43
Filip Kraljević,17,2.43,2,0.29
Klavs Čavars,13,1.86,4,0.57
Cyril Langevine,9,1.13,6,0.75
Kavell Bigby-Williams,9,1.29,2,0.29
...,...,...,...,...
Jakub Nizioł,0,0.00,2,0.29
Tomasz Śnieg,0,0.00,1,0.14
Marek Klassen,0,0.00,5,0.71
Filip Małgorzaciak,0,0.00,1,0.14
James Florence,0,0.00,2,0.29

In [61]:
# Łączenie dataframes

In [62]:
df = pd.concat([mecze,czas_gry,punkty,rzuty_z_gry,rzuty_za_2,rzuty_za_3,rzuty_wolne,zbiorki,asysty,przechwyty,bloki,faule], axis=1, ignore_index=False)
df

,Drużyna,Mecze,Czas gry suma,Czas gry śr.,Punkty suma,Punkty śr.,Celne rzuty z gry suma,Celne rzuty z gry śr.,Oddane rzuty z gry suma,Oddane rzuty z gry śr.,...,Przechwyty suma,Przechwyty śr,Bloki suma,Bloki śr,Bloki otrzymane suma,Bloki otrzymane śr,Faule suma,Faule śr.,Faule wymuszone suma,Faule wymuszone śr.
Zawodnik,,,,,,,,,,,,,,,,,,,,,
A.j. English,HydroTruck Radom,7,233:16,33:19,153,21.86,47.0,6.7,99.0,14.1,...,7,1.00,2,0.29,3,0.43,18,2.57,36,5.14
William Garrett,Grupa Sierleccy Czarni Słupsk,7,243:15,34:45,142,20.29,46.0,6.6,106.0,15.1,...,11,1.57,2,0.29,4,0.57,15,2.14,42,6.00
Jabarie Hinds,GTK Gliwice,7,233:02,33:17,137,19.57,47.0,6.7,95.0,13.6,...,7,1.00,2,0.29,7,1.00,7,1.00,31,4.43
Stacy Davis,King Szczecin,7,228:15,32:36,127,18.14,48.0,6.9,99.0,14.1,...,7,1.00,7,1.00,8,1.14,12,1.71,20,2.86
Michael Moore,HydroTruck Radom,8,261:07,32:38,126,15.75,47.0,5.9,106.0,13.3,...,11,1.38,3,0.38,6,0.75,22,2.75,22,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Błażej Kulikowski,Grupa Sierleccy Czarni Słupsk,6,29:43,04:57,1,0.17,NaN,NaN,NaN,NaN,...,0,0.00,0,0.00,0,0.00,4,0.67,1,0.17
Rafał Komenda,Anwil Włocławek,4,04:02,01:01,0,0.00,NaN,NaN,NaN,NaN,...,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00
Szymon Kołakowski,Legia Warszawa,4,07:59,02:00,0,0.00,NaN,NaN,NaN,NaN,...,1,0.25,0,0.00,0,0.00,2,0.50,0,0.00
Marcin Woroniecki,Anwil Włocławek,6,03:49,00:38,0,0.00,NaN,NaN,NaN,NaN,...,0,0.00,0,0.00,0,0.00,0,0.00,0,0.00
Adrian Kordalski,Grupa Sierleccy Czarni Słupsk,4,18:03,04:31,0,0.00,NaN,NaN,NaN,NaN,...,0,0.00,0,0.00,0,0.00,1,0.25,0,0.00

In [63]:
df.shape

(159, 44)

In [64]:
df.head()

,Drużyna,Mecze,Czas gry suma,Czas gry śr.,Punkty suma,Punkty śr.,Celne rzuty z gry suma,Celne rzuty z gry śr.,Oddane rzuty z gry suma,Oddane rzuty z gry śr.,...,Przechwyty suma,Przechwyty śr,Bloki suma,Bloki śr,Bloki otrzymane suma,Bloki otrzymane śr,Faule suma,Faule śr.,Faule wymuszone suma,Faule wymuszone śr.
Zawodnik,,,,,,,,,,,,,,,,,,,,,
A.j. English,HydroTruck Radom,7,233:16,33:19,153,21.86,47.0,6.7,99.0,14.1,...,7,1.00,2,0.29,3,0.43,18,2.57,36,5.14
William Garrett,Grupa Sierleccy Czarni Słupsk,7,243:15,34:45,142,20.29,46.0,6.6,106.0,15.1,...,11,1.57,2,0.29,4,0.57,15,2.14,42,6.00
Jabarie Hinds,GTK Gliwice,7,233:02,33:17,137,19.57,47.0,6.7,95.0,13.6,...,7,1.00,2,0.29,7,1.00,7,1.00,31,4.43
Stacy Davis,King Szczecin,7,228:15,32:36,127,18.14,48.0,6.9,99.0,14.1,...,7,1.00,7,1.00,8,1.14,12,1.71,20,2.86
Michael Moore,HydroTruck Radom,8,261:07,32:38,126,15.75,47.0,5.9,106.0,13.3,...,11,1.38,3,0.38,6,0.75,22,2.75,22,2.75

### Sprawdzamy czy w df są jakieś brakuące dane

In [65]:
df.isnull().sum()

Drużyna                     0
Mecze                       0
Czas gry suma               0
Czas gry śr.                0
Punkty suma                 0
Punkty śr.                  0
Celne rzuty z gry suma     23
Celne rzuty z gry śr.      23
Oddane rzuty z gry suma    23
Oddane rzuty z gry śr.     23
Skuteczność z gry          23
Celne rzuty za 2 suma      46
Celne rzuty za 2 śr.       46
Oddane rzuty za 2 suma     46
Oddane rzuty za 2 śr.      46
Skuteczność za 2           46
Celne rzuty za 3 suma      68
Celne rzuty za 3 śr.       68
Oddane rzuty za 3 suma     68
Oddane rzuty za 3 śr.      68
Skuteczność za 3           68
Celne rzuty wolne suma     93
Celne rzuty wolne śr.      93
Oddane rzuty wolne suma    93
Oddane rzuty wolne śr.     93
Skuteczność za 1           93
Zbiórki w ataku suma        0
Zbiórki w ataku śr.         0
Zbiórki w obronie suma      0
Zbiórki w obronie śr.       0
Zbiórki suma                0
Zbiórki śr                  0
Asysty suma                 0
Asysty śr.                  0
Przechwyty suma             0
Przechwyty śr               0
Bloki suma                  0
Bloki śr                    0
Bloki otrzymane suma        0
Bloki otrzymane śr          0
Faule suma                  0
Faule śr.                   0
Faule wymuszone suma        0
Faule wymuszone śr.         0
dtype: int64

### Niektórzy zawodnicy nie mają poszczególnych danych. Przypisujemy im wartość "0".

In [66]:
df = df.fillna(0)

In [67]:
df.isnull().sum()

Drużyna                    0
Mecze                      0
Czas gry suma              0
Czas gry śr.               0
Punkty suma                0
Punkty śr.                 0
Celne rzuty z gry suma     0
Celne rzuty z gry śr.      0
Oddane rzuty z gry suma    0
Oddane rzuty z gry śr.     0
Skuteczność z gry          0
Celne rzuty za 2 suma      0
Celne rzuty za 2 śr.       0
Oddane rzuty za 2 suma     0
Oddane rzuty za 2 śr.      0
Skuteczność za 2           0
Celne rzuty za 3 suma      0
Celne rzuty za 3 śr.       0
Oddane rzuty za 3 suma     0
Oddane rzuty za 3 śr.      0
Skuteczność za 3           0
Celne rzuty wolne suma     0
Celne rzuty wolne śr.      0
Oddane rzuty wolne suma    0
Oddane rzuty wolne śr.     0
Skuteczność za 1           0
Zbiórki w ataku suma       0
Zbiórki w ataku śr.        0
Zbiórki w obronie suma     0
Zbiórki w obronie śr.      0
Zbiórki suma               0
Zbiórki śr                 0
Asysty suma                0
Asysty śr.                 0
Przechwyty suma            0
Przechwyty śr              0
Bloki suma                 0
Bloki śr                   0
Bloki otrzymane suma       0
Bloki otrzymane śr         0
Faule suma                 0
Faule śr.                  0
Faule wymuszone suma       0
Faule wymuszone śr.        0
dtype: int64

## Sprawdzamy występujące wartości w kolumnach, gdzie występują wartości typu string

In [68]:
list(df["Drużyna"].unique())

['HydroTruck Radom ',
 'Grupa Sierleccy Czarni Słupsk ',
 'GTK Gliwice ',
 'King Szczecin ',
 'Anwil Włocławek ',
 'MKS Dąbrowa Górnicza ',
 'Enea Zastal BC Zielona Góra ',
 'Polski Cukier Pszczółka Start Lublin ',
 'Trefl Sopot ',
 'Twarde Pierniki Toruń ',
 'Legia Warszawa ',
 'PGE Spójnia Stargard ',
 'Arged BM Stal Ostrów Wlkp. ',
 'WKS Śląsk Wrocław ',
 'Asseco Arka Gdynia ',
 'Enea Abramczyk Astoria Bydgoszcz ',
 'Asseco Arka Gdynia, Grupa Sierleccy Czarni Słupsk ']

In [69]:
df[df["Drużyna"] == 'Asseco Arka Gdynia, Grupa Sierleccy Czarni Słupsk ']

,Drużyna,Mecze,Czas gry suma,Czas gry śr.,Punkty suma,Punkty śr.,Celne rzuty z gry suma,Celne rzuty z gry śr.,Oddane rzuty z gry suma,Oddane rzuty z gry śr.,...,Przechwyty suma,Przechwyty śr,Bloki suma,Bloki śr,Bloki otrzymane suma,Bloki otrzymane śr,Faule suma,Faule śr.,Faule wymuszone suma,Faule wymuszone śr.
Zawodnik,,,,,,,,,,,,,,,,,,,,,
Bartosz Jankowski,"Asseco Arka Gdynia, Grupa Sierleccy Czarni Słu...",4,89:29,22:22,29,7.25,9.0,2.3,19.0,4.8,...,2,0.5,0,0.0,1,0.25,6,1.5,6,1.5

### Bartosz Jankowski należy do Asseco Arka Gdynia

In [70]:
df[df["Drużyna"] == 'Asseco Arka Gdynia, Grupa Sierleccy Czarni Słupsk '] = df[df["Drużyna"] == 'Asseco Arka Gdynia, Grupa Sierleccy Czarni Słupsk '].replace({
    'Asseco Arka Gdynia, Grupa Sierleccy Czarni Słupsk ':'Asseco Arka Gdynia',
})

In [71]:
df[df["Drużyna"] == 'Asseco Arka Gdynia, Grupa Sierleccy Czarni Słupsk '] # Wartość została naprawiona

Empty DataFrame
Columns: [Drużyna, Mecze, Czas gry suma, Czas gry śr., Punkty suma, Punkty śr., Celne rzuty z gry suma, Celne rzuty z gry śr., Oddane rzuty z gry suma, Oddane rzuty z gry śr., Skuteczność z gry, Celne rzuty za 2 suma, Celne rzuty za 2 śr., Oddane rzuty za 2 suma, Oddane rzuty za 2 śr., Skuteczność za 2, Celne rzuty za 3 suma, Celne rzuty za 3 śr., Oddane rzuty za 3 suma, Oddane rzuty za 3 śr., Skuteczność za 3, Celne rzuty wolne suma, Celne rzuty wolne śr., Oddane rzuty wolne suma, Oddane rzuty wolne śr., Skuteczność za 1, Zbiórki w ataku suma, Zbiórki w ataku śr., Zbiórki w obronie suma, Zbiórki w obronie śr., Zbiórki suma, Zbiórki śr, Asysty suma, Asysty śr., Przechwyty suma, Przechwyty śr, Bloki suma, Bloki śr, Bloki otrzymane suma, Bloki otrzymane śr, Faule suma, Faule śr., Faule wymuszone suma, Faule wymuszone śr.]
Index: []

[0 rows x 44 columns]

### Udostępniamy/ pozwalamy na przechowywanie "df" w bazie danych, poza tym plikiem.

In [72]:
%store df

Stored 'df' (DataFrame)

In [73]:
df.loc['Bartosz Jankowski']

Drużyna                    Asseco Arka Gdynia
Mecze                                       4
Czas gry suma                           89:29
Czas gry śr.                            22:22
Punkty suma                                29
Punkty śr.                               7.25
Celne rzuty z gry suma                    9.0
Celne rzuty z gry śr.                     2.3
Oddane rzuty z gry suma                  19.0
Oddane rzuty z gry śr.                    4.8
Skuteczność z gry                        47.4
Celne rzuty za 2 suma                     0.0
Celne rzuty za 2 śr.                      0.0
Oddane rzuty za 2 suma                    0.0
Oddane rzuty za 2 śr.                     0.0
Skuteczność za 2                          0.0
Celne rzuty za 3 suma                     5.0
Celne rzuty za 3 śr.                      1.3
Oddane rzuty za 3 suma                   12.0
Oddane rzuty za 3 śr.                     3.0
Skuteczność za 3                         41.7
Celne rzuty wolne suma                    0.0
Celne rzuty wolne śr.                     0.0
Oddane rzuty wolne suma                   0.0
Oddane rzuty wolne śr.                    0.0
Skuteczność za 1                          0.0
Zbiórki w ataku suma                        3
Zbiórki w ataku śr.                       0.8
Zbiórki w obronie suma                      9
Zbiórki w obronie śr.                     2.3
Zbiórki suma                               12
Zbiórki śr                                3.0
Asysty suma                                 7
Asysty śr.                                1.8
Przechwyty suma                             2
Przechwyty śr                             0.5
Bloki suma                                  0
Bloki śr                                  0.0
Bloki otrzymane suma                        1
Bloki otrzymane śr                       0.25
Faule suma                                  6
Faule śr.                                 1.5
Faule wymuszone suma                        6
Faule wymuszone śr.                       1.5
Name: Bartosz Jankowski, dtype: object